### PR TITLE
Feat/knowledge graph analysis

### PR DESCRIPTION
**Pull request by vvrahul11**
**Summary**
A folder '[09.knowledge-graph-analysis](https://github.com/jump-cellpainting/2024_Chandrasekaran_Morphmap/tree/feat/knowledge-graph-analysis/09.knowledge-graph-analysis)' is added to link Evotec's KG analysis github repository to parent Morphmap repository. 

**TODO:** We will add one paragraph summarizing this analysis with a figure later.

### CODE REVIEW

**Comment by niranjchandrasekaran** [comment]
Thanks @vvrahul11! It looks like https://github.com/Evotec-isRD/GNN-MorphMap isn't public yet. Once it is public, I will merge this PR.

**Comment by niranjchandrasekaran** [comment]
Hi @vvrahul11, would you be able to make https://github.com/Evotec-isRD/GNN-MorphMap public? I can then merge this PR. Thanks!

**Comment by vvrahul11** [comment]
> Hi @vvrahul11, would you be able to make https://github.com/Evotec-isRD/GNN-MorphMap public? I can then merge this PR. Thanks!

Hi @niranjchandrasekaran, Sorry for the delay. We made the repository public. You should be able to access it now. Thanks. 
https://github.com/Evotec-isRD/GNN-MorphMap

**Comment by niranjchandrasekaran** [comment]
Thank you, @vvrahul11!

**Pull request merged**
